#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define EXERCISE_NUMBER 	1 //WHEN YOU FINISH EACH EXERCISE, INCREMENT THIS VALUE

bool button1_pushed; //flag to store button1 input
bool button2_pushed; //flag to store button2 input


/* monitorInput()
*
*  Used to flag button inputs
*       - this avoids errors caused by program recognizing input, taking action, and
*         reading input again before button is released
*/
void monitorInput()
{
  if(SensorValue(button1) && !button1_pushed)
  {
    button1_pushed = true;
  }

  if(SensorValue(button2) & !button2_pushed)
  {
    button2_pushed = true;
  }
}

void exercise_1()
{

	while(true)
	{
		monitorInput();
		if( button1_pushed ) {
		/* INSERT CODE HERE
		  	  * - IMPORTANT: WHEN YOU SET UP YOUR PUSH BUTTONS, YOU MUST NAME THEM "button1"
		  	  * - AND "button2" or you will get compiler errors when you attempt to run your code
		  	  * - make sure EXERCISE_NUMBER is set to 1
		  	  * - turn motor on and clear button1_pushed flag
		  	  * - wait for button2 push
		  	  * - turn motor off, and clear flag again
		  	  */
		} // end if
	}//end while
}

void exercise_2()
{
  while(true)
  {
    monitorInput();

    if(button1_pushed)
		{
		  /* INSERT CODE HERE
		  * - Make sure EXERCISE_NUMBER is set to 2
		  * - turn motor on and clear button1_pushed flag
		  * - wait for time to expire
		  * - turn motor off
		  */
     } // end if
    }// end while

} // end exercise_2

void exercise_3()
{
	while(true)
	{
	  monitorInput();

    if(button1_pushed)
		{
      /* INSERT CODE HERE
      * - make sure EXERCISE_NUMBER is set to 3
		  * - reset rotation sensor
      * - turn motor on
		  * - wait for rotation to reach 720
		  * - turn motor off, and clear button1_pushed flag
		  */

      }//end if
  }//end while

}//end exercse_3

void exercise_4()
{
  while(true)
  {
    monitorInput();
    /* INSERT CODE HERE
		* - use FSM design and methods used in previous exercises
		*   to achieve desired system behviour
		*/
  }//end while
}

task main()
{
	button1_pushed = button2_pushed = false;

	switch (EXERCISE_NUMBER)
  {
     case 1:
       exercise_1();
       break;
     case 2:
       exercise_2();
       break;
     case 3:
       exercise_3();
       break;
     case 4:
       exercise_4();
       break;
     default: //should never get here.
   } // end switch

}// end main
